### PR TITLE
Display cards

### PR DESCRIPTION
**Pull request by rbeaujon**
Added styles on display of cards on Events Page #93

### CODE REVIEW

**Comment by Rahul5430** [comment]
hi @rbeaujon, please provide a screenshot of the page before and after the changes are made and also take a fresh pull after your previous PR was merged.

**Comment by rbeaujon** [comment]
Done I created a new PR and added the screenshots on it

**Comment by Rahul5430** [comment]
ok then you can close this PR

**Comment by rbeaujon** [comment]
The last one?  Display cards?

**Pull request merged**
