### PR TITLE
Footer Redesigned

### LINKED ISSUE #74: Create a Matching Footer in the Site
Site Theme
image

Current Footer
image

I will create a matching footer for the site 
assign this task to me

### PR DESCRIPTION
**Pull request by vaibhava17**
Created a footer with the same colors and style & it is responsive as well

### Web View
image

### Mobile View
image

### CODE REVIEW

**Comment by HarshDutt17** [comment]
Since most of the pages have a white background, having footer of white background as well doesn't appear appealing. I would recommend you to use black background, white text, and for icons and emphasising content use the blue shades.

Instead of mentioning keywords "address", "Phone No", "website", use icons to convey the same meanings.

For footer don't use the header font, as header requires spaced titles for ease navigation, whereas using it in footer makes it appear to use extra space without any significance

**Comment by vaibhava17** [comment]
@HarshDutt17 ok

**Comment by vaibhava17** [comment]
@HarshDutt17 can you provide me a transparent background logo of this site 
image

**Comment by vaibhava17** [comment]
@HarshDutt17 
Design fixes done

**added a font awesome CDN in `public/index.html`**

### Mobile View
image

### Web View
image

**Review by HarshDutt17 — APPROVED** [review]

**Pull request merged**
