### PR TITLE
feat(projectCard): add toggle height for project card

### PR DESCRIPTION
**Pull request by nitoC**
created a project card CSS file to achieve this

### CODE REVIEW

**Review by anujawas — COMMENTED** [review]
Add Screenshot for the respective changes

**Comment by nitoC** [comment]
Captureheight

**Comment by nitoC** [comment]
Captureheight1

**Comment by nitoC** [comment]
changing the card image height on expansion will affect the image dimension which is a bad design so I changed and removed the image stretch.

**Review by anujawas — APPROVED** [review]

**Pull request merged**
